# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hulk' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hulk
  pod 'SnapKit', '~> 3.1.2'
  pod 'Alamofire', '~> 4.0'

  target 'HulkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HulkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
